spring:
  datasource:
    url: jdbc:postgresql://localhost:13551/mydatabase
    username: marcin
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/db-changelog.xml
    default-schema: public

#  docker:
#    compose:
#      skip:
#        in-tests: false
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace